version: '3.7'

networks:
  web-ctm-app-net:
    name: my-ctm-web-app-net
    driver: bridge
    external: true

services:
  # ctm-app service
  backend-app:
    container_name: ctm-backend
    image: 'ctm-app-backend'
    build:
      context: "./"
      #args:
      #- APP_ENV=${APP_ENV}
      dockerfile: "Dockerfile"
    restart: always
    environment:
      - TZ=Asia/Dhaka
    extra_hosts:
      - "prportal.nidw.gov.bd:192.168.66.2"
      - "ssnapi.finance.gov.bd:43.229.14.106"
    ports:
      - "8060:80"
    networks:
      - web-ctm-app-net
